version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "80:80"
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - php
    restart: always
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    ports:
      - ":9000"
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    depends_on:
      - mariadb
  phpmyadmin:
    image: sk278/phpmyadmin-armhf
    ports:
     - "8080:8080"
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI="http://localhost/phpmyadmin"
    depends_on:
      - mariadb
    networks:
      - internal
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'librarysystemroot123'
      MYSQL_USER: 'authenticator'
      MYSQL_PASSWORD: 'library'
      MYSQL_DATABASE: 'libraryDB'
      MYSQL_HOST: '127.0.0.1'
    ports:
      - "3306:3306"
    networks:
     - internal
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata: {}
networks:
  internal:
    driver: bridge